#!/bin/bash

export PODMAN_USERNS=keep-id

if [[ -f "./docker-compose.yml" ]]; then 
    STACK_DIR="./"
elif [[ -f "./stack/docker-compose.yml" ]]; then
    STACK_DIR="./stack"
else
    echo "Did not find a valid stack path!"
    exit
fi

podman-compose -f "$STACK_DIR/docker-compose.yml" "$@"
