#!/bin/bash

DESPO_CONF_PATH=$1.yml

export ESPOCRM_PROJECT_NAME=$(yq -r .name $DESPO_CONF_PATH)
export ESPOCRM_INSTALL_PATH=$(yq -r .path $DESPO_CONF_PATH)
export ESPOCRM_PORT=$(yq -r .port $DESPO_CONF_PATH)

export ESPOCRM_DB_ROOT_PASS=$(yq -r .db.root_pass $DESPO_CONF_PATH)
export ESPOCRM_DB_NAME=$(yq -r .db.name $DESPO_CONF_PATH)
export ESPOCRM_DB_USER=$(yq -r .db.user $DESPO_CONF_PATH)
export ESPOCRM_DB_PASS=$(yq -r .db.pass $DESPO_CONF_PATH)
export ESPOCRM_DB_PORT=$(yq -r .db.port $DESPO_CONF_PATH)
export ESPOCRM_DB_DATA_DIR=${ESPOCRM_INSTALL_PATH}/build/mysql

export PODMAN_USERNS=keep-id

docker-compose -p ${ESPOCRM_PROJECT_NAME} "${@:2}"