version: '3'

services:
  mysql:
    image: mysql:8
    container_name: espocrm-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${ESPOCRM_DB_ROOT_PASS:-root_password}
      MYSQL_DATABASE: ${ESPOCRM_DB_NAME:-espocrm}
      MYSQL_USER: ${ESPOCRM_DB_USER:-espocrm}
      MYSQL_PASSWORD: ${ESPOCRM_DB_PASS:-espocrm}
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - ${ESPOCRM_DB_PORT:-3306}:3306

  espocrm:
    image: espocrm/dev
    build:
      context: ./
    container_name: espocrm-dev
    volumes:
      - ./espocrm:/app
      - ./extensions:/home/espo/extensions
    restart: always
    ports:
      - ${ESPOCRM_PORT:-8080}:80