version: '3'

services:
  mysql:
    image: mysql:8
    container_name: espocrm-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${ESPOCRM_DB_ROOT_PASS:-root_password}
      MYSQL_DATABASE: ${ESPOCRM_DB_NAME:-espocrm}
      MYSQL_USER: ${ESPOCRM_DB_USER:-espocrm}
      MYSQL_PASSWORD: ${ESPOCRM_DB_PASS:-espocrm}
    volumes:
      - ../data/mysql:/var/lib/mysql
    restart: always
    ports:
      - ${ESPOCRM_DB_PORT:-3306}:3306

  espocrm:
    image: espocrm/dev
    build:
      context: ./docker
    container_name: espocrm-dev
    volumes:
      - ./docker/conf/etc/supervisor.d/watcher.conf:/opt/docker/etc/supervisor.d/watcher.conf
      - ./docker/scripts:/home/espo/scripts
      - ../espocrm:/home/espo/app
      - ../extensions:/home/espo/extensions
      - ../data/espo/data:/app/data
      #- ../data/espo/custom:/app/custom
      #- ../data/espo/client/custom:/app/client/custom
    restart: always
    ports:
      - ${ESPOCRM_PORT:-8080}:80